Add instructions for pushing to GitHub from the VEDA Hub
NASA-IMPACT/veda-docs pull request #158
Opened 2024-08-06 22:31 UTC by maxrjones

This PR adds a new section to `Usage Examples` called `JupyterHub`. It currently contains one markdown file `How to push to GitHub from the VEDA JupyterHub` but I think the new section would be helpful for other upcoming improvements (e.g., additional IDEs). While there's some redundancy with the 2i2c docs, I think the 2i2c docs offer cover background and reasons for things being done a certain way (which is useful for their audience), whereas these how-to guides would provide the minimal required explanation for solving a user's problem.

2024-08-15 20:26 UTC, jsignell reviewed
This looks good, but I did get an error. Probably something that I had set up already that conflicts:

```
warning: credential.https://github.com.helper has multiple values
error: cannot overwrite multiple values with a single value
       Use a regexp, --add or --replace-all to change credential.https://github.com.helper.
```
Full error:

![image](https://github.com/user-attachments/assets/20ad22f9-58d2-4835-9ffc-0b41212f883c)

2024-08-15 20:26 UTC, jsignell commented on notebooks/quickstarts/github-authentication.md
> +    - If a requested does not have sufficient permissions, GitHub will send a notification to the organization owner requesting that they install the app.
```suggestion
    - If you do not have sufficient permissions, GitHub will send a notification to the organization owner requesting that they install the app.
```

2024-08-15 20:58 UTC, maxrjones commented
Thanks for the review @jsignell! @wildintellect mentioned that this setup may still be confusing to users, so I'm going to try out recording a quick video explanation (hopefully tomorrow). So, I'll hold off on merging this for a short while and may ping you for another review.

that error does seem likely relating to an existing setup. I can add a warning and perhaps we should also include a section in the JupyterHub section of the docs on where users can go to reach out for help. Is the IMPACT slack where that help would happen?

2024-08-15 21:29 UTC, wildintellect commented
Step 1. Clarify that an Org admin has to setup the initial permissions.
Step 2.
> Second, you need to authorize the app on the Hub. This needs to be done once every 8 hours. 
Does every user need to do this? So basically it's once per working day?
Can we include `gh-scoped-creds.ipynb` in the docs repo, so that users just need to open it and run it? (we already checkout the docs in Pangeo workspaces)

The whole thing feels reverse order for actual user usage.
1. Remember to clone your repos with https, NOTE: github token is the alternative to this method
2. Authorize once per day (Every 8 hours) <- I wonder if we could make a widget or if the jupyter github extension incorporates this
3. First time Config for Repos/Organizations (maybe mention at top and link to bottom?

2024-08-15 21:29 UTC, wildintellect requested changes
See previous comment thread.

2024-10-31 20:00 UTC, wildintellect commented
@maxrjones looks close I think the only thing missing is a copy of that notebook in the PR that goes into notebooks/templates ? open to other location ideas. I just don't want it to only exist in the shared folder on VEDA where it can go missing.

2024-10-31 20:12 UTC, maxrjones commented
> @maxrjones looks close I think the only thing missing is a copy of that notebook in the PR that goes into notebooks/templates ? open to other location ideas. I just don't want it to only exist in the shared folder on VEDA where it can go missing.

It's just two lines of code which are shown in the GIF. Also, only admins should be able to modify the `shared-readwrite` directory, so I think the risk here is minimal.

Relatedly, could you please create that notebook in `shared-readwrite`? I would offer to become an admin, but I actually think it's useful for me to have the same experience as a typical VEDA user.

2024-11-11 19:56 UTC, maxrjones commented
> > @maxrjones looks close I think the only thing missing is a copy of that notebook in the PR that goes into notebooks/templates ? open to other location ideas. I just don't want it to only exist in the shared folder on VEDA where it can go missing.
> 
> It's just two lines of code which are shown in the GIF. Also, only admins should be able to modify the `shared-readwrite` directory, so I think the risk here is minimal.
> 
> Relatedly, could you please create that notebook in `shared-readwrite`? I would offer to become an admin, but I actually think it's useful for me to have the same experience as a typical VEDA user.

@wildintellect do you think we could merge this PR? a Hub user is asking about sharing code and I think these instructions could be helpful

2024-11-12 17:53 UTC, wildintellect commented
@maxrjones another reason to put it in the repo, this code will actually get checkout to instances and we won't need to manage `shared-public/shared-rewrite`.

2024-11-13 20:21 UTC, maxrjones commented
> @maxrjones another reason to put it in the repo, this code will actually get checkout to instances and we won't need to manage `shared-public/shared-rewrite`.

OK, done

2024-11-13 21:35 UTC, wildintellect commented on nasa-veda-platform/scientific-computing/github-authentication.qmd
> +You need to do this step each time you create a new JupyterHub instance.
Create or Boot (start)? I feel like the word could be confusing, but maybe I'm overthinking.

2024-11-13 21:36 UTC, wildintellect commented on nasa-veda-platform/scientific-computing/github-authentication.qmd
> +This will only allow pushing to repositories that have been [configured with the veda-hub-github-scoped-creds-app]()
Is this supposed to be a link to something?

Now I recall this step is the reason that I wanted to note Personal Access Tokens as a common alternative that doesn't require Org level admins to approve.

2024-11-13 21:41 UTC, wildintellect commented on nasa-veda-platform/scientific-computing/github-authentication.qmd
> +This will only allow pushing to repositories that have been [configured with the veda-hub-github-scoped-creds-app]()
It should say something like. This is the recommend method on VEDA, but if you're having issues you can fallback on this method. https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens that works everywhere.

2024-11-13 22:26 UTC, wildintellect approved these changes

2024-11-14 00:51 UTC, merged