Add page of external resources
NASA-IMPACT/veda-docs pull request #18
Opened 2023-02-24 16:25 UTC by jsignell

Closes https://github.com/NASA-IMPACT/veda-analytics/issues/23
Looks like: 
![image](https://user-images.githubusercontent.com/4806877/221232162-3f1d86e2-74c0-4279-8245-95b678d78c91.png)

2023-02-25 21:00 UTC, j08lue requested changes
I suggested a few changes, with the goal of making it very obvious to readers, who the list is intended for, and making the headings by themselves already instructional, so readers can see at a glance what type of resources or learnings we are recommending.

Please feel free to accept or adapt my suggestions, or let me know if you generally do not like the new format I am suggesting.

2023-02-25 21:00 UTC, j08lue commented on external-resources.qmd
> +subtitle: "List of resources for learning more about open source geospatial tools in Python"
```suggestion
subtitle: "Learn more about tools and practice open source geospatial data science - a list of external resources to get you started"
```

2023-02-25 21:00 UTC, j08lue commented on external-resources.qmd
> +## Workflow resources
```suggestion
## Master the basic workflow tools
```

2023-02-25 21:00 UTC, j08lue commented on external-resources.qmd
> +## Geospatial courses/books
```suggestion
## Take a course or read a book on geospatial data analysis
```

2023-02-25 21:00 UTC, j08lue commented on external-resources.qmd
> +## Geospatial docs
```suggestion
## Look through nicely curated lists of tools and resources
```

2023-02-25 21:00 UTC, j08lue commented on external-resources.qmd
> +## Materials from hack weeks
```suggestion
## Find out what a Hack Week is and see how they teach best practice
```

2023-02-25 21:00 UTC, j08lue commented on external-resources.qmd
> +## Blogs
```suggestion
## Stay up-to-date through blogs
```

2023-02-25 21:00 UTC, j08lue commented on external-resources.qmd
> +
```suggestion

This list is intended for (aspiring) scientists who want to get started with cloud-based, collaborative, open geospatial data analysis, or those looking to refresh their knowledge. It is by no means complete, but contains pointers to more elaborate resources. We anticipate this list to evolve as our platform and use cases evolve. Suggestions for additional resources or topics are highly welcome.

```

2023-02-27 14:19 UTC, jsignell commented
No I think this is great! I was mostly thinking about what would be helpful groupings but lost sight of explaining how this page is actually intended to be used :facepalm: Thanks for the suggestions @j08lue!

2023-02-27 21:24 UTC, j08lue approved these changes

2023-02-28 16:23 UTC, merged